# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('ERGC', ['network', 'energy', 'mobility', 'internet','applications','aqua-sim-ng'])
    module.source = [
        'model/ergc.cc',
        'model/ergc-application.cc',
        'model/ergc-routing.cc',
        'model/ergc-headers.cc',
        'helper/ergc-application-helper.cc',
        'helper/ergc-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('ERGC')
    module_test.source = [
        'test/ergc-test-suite.cc',
        ]
    # Tests encapsulating example programs should be listed here
    if (bld.env['ENABLE_EXAMPLES']):
        module_test.source.extend([
        #    'test/ERGC-examples-test-suite.cc',
             ])

    headers = bld(features='ns3header')
    headers.module = 'ERGC'
    headers.source = [
        'model/ergc.h',
        'model/ergc-application.h',
        'model/ergc-headers.h',
        'model/ergc-routing.h',
        'helper/ergc-application-helper.h',
        'helper/ergc-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

